### ISSUE TITLE
bug: error reported when use v0.5.0

### ISSUE THREAD

**Issue by ben1009** [rust-cli/anstyle#118] opened 2023-08-25 08:38 UTC
error as below
```
rustc --version
rustc 1.70.0-nightly (171693274 2023-03-14)
```
<img width="752" alt="image" src="https://github.com/rust-cli/anstyle/assets/1741864/5d7af841-f9d1-416d-9c88-8cb4bf9409ff">

**Comment by mucks-cdc** [comment] 2023-08-25 10:22
having the same problem with rustc 1.70.0-nightly (da7c50c08 2023-03-19)

**Comment by epage** [comment] 2023-08-25 11:16
Is that nightly from before IsTerminal was stabilized? To be safest, id recommend a 1.71 nightly (assuming you have a hard requirement on nightly).

**Comment by aminya** [comment] 2023-08-27 10:26
I am having the same issue. Does this mean that this package only works on nightly?

**Comment by IceTDrinker** [comment] 2023-08-28 09:53
looks like the package uses unstable features in every situation making it incompatible with stables toolchains, is it expected ?

hitting the same error via transitives deps

**Comment by epage** [comment] 2023-08-28 13:42
@aminya 
> I am having the same issue. Does this mean that this package only works on nightly?

The package works with stable releases starting with 1.70.0.

**Comment by mataha** [comment] 2023-08-28 13:43
> I am having the same issue. Does this mean that this package only works on nightly?

Definitely not - I can confirm that latest stable works:

```batchfile
> rustc --version
rustc 1.71.0 (8ede3aae2 2023-07-12)
```

**Comment by epage** [comment] 2023-08-28 13:45
@IceTDrinker 

> hitting the same error via transitives deps
> 
> `info: latest update on 2023-04-12, rust version 1.70.0-nightly (9df3a39fb 2023-04-11)`

Note you are using a **nightly** of 1.70 which means you are dependent on when the feature was merged.  It looks like the [tracking issue was closed on April 13th](https://github.com/rust-lang/rust/issues/98070), so if you are needing a nightly, it would need to be at earliest an April 13th but it might need to be 14th or later, depending on whether it missed a cutoff for building a specific nightly.

Since this is just a problem with people using 1.70.0-nightlies that are too early, I'm closing this.

**Closed by epage** 2023-08-28 13:45 UTC

**Comment by IceTDrinker** [comment] 2023-08-28 13:59
yes my bad @epage thanks for the quick answer !
